graph = JanusGraphFactory.open("/code/janusgraph.properties")
graph.tx().rollback()
mgmt = graph.openManagement()
airport = mgmt.getVertexLabel('airport')
d = mgmt.getPropertyKey('desc')
mgmt.buildIndex('descMixedIndex', Vertex.class).addKey(d).indexOnly(airport).buildMixedIndex('search')
mgmt.commit()
mgmt.awaitGraphIndexStatus(graph, 'descMixedIndex').call()
mgmt = graph.openManagement()
mgmt.updateIndex(mgmt.getGraphIndex("descMixedIndex"), SchemaAction.REINDEX).get()
mgmt.commit()